FROM python:3.9-slim
WORKDIR /app

RUN python -m venv venv
ENV PATH="/app/venv/bin:$PATH"

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src
COPY assets/ ./assets

ENTRYPOINT ["python", "src/cli.py"]